# Name of this GitHub Actions workflow.
name: Generate 4.0 Outputs

on:
  # Scan on workflow call
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan when pushing to master
  push:
    paths:
      - "4.0/**"
        #branches: ["master", "main"]
        #

jobs:
  prepare_outputs:
    runs-on: ubuntu-latest
    name: Generate 4.0 outputs
    steps:
      - uses: docker/login-action@v2.2.0
        with: 
          registry: ghcr.io 
          username: ${{ secrets.GHCR_USERNAME }} 
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: actions/checkout@v3
      - run: make 4.0
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ASVS 4.0
          path: 4.0/docs_*
