name: Markdown Linter

on: [push, pull_request]

jobs:
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: './5.0*'
          config_file: ".markdownlint.jsonc"
          ignore_files: "tools, templates, images"
