# This workflow uploads the generated English 5.0 documents to the 'latest' GitHub release.
name: Publish 5.0 English Docs to Latest Release

on:
  workflow_call:

jobs:
  publish-5-0-english-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Download 5.0 English artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ASVS 5.0.0
          path: ./asvs-5.0-english
      - name: Upload to 'latest' GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest 5.0 English Documents
          files: ./asvs-5.0-english/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
